Added sonarcloud integration
canonical/juju-verify pull request #148
Opened 2022-11-10 11:25 UTC by esunar

Results will be available [here](https://sonarcloud.io/project/overview?id=juju-verify)

2022-11-10 12:02 UTC, rgildein requested changes

2022-11-10 12:02 UTC, rgildein commented on .github/sonar.yml
> +          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
missing new line at the end of the file

2022-11-10 12:02 UTC, rgildein commented on sonar-project.properties
> +sonar.coverage.exclusions=tests/**, docs/**, contrib/**, snap/**, *
missing new line at the end of the file

2022-11-10 14:02 UTC, esunar commented on .github/sonar.yml
> +        run: make unittests
to create covarage.xml file

2022-11-10 14:06 UTC, esunar commented on .github/sonar.yml
> +      - uses: actions/checkout@v2
it is sonarcloud's recommended

2022-11-10 14:10 UTC, esunar commented on sonar-project.properties
> +sonar.coverage.exclusions=tests/**, docs/**, contrib/**, snap/**, *
fixed

2022-11-10 14:10 UTC, esunar commented on sonar-project.properties
> +
fixed

2022-11-10 14:10 UTC, esunar commented on .github/sonar.yml
> +          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
fixed

2022-11-10 14:10 UTC, esunar commented on .github/sonar.yml
> +name: Build
fixed

2022-11-10 14:11 UTC, esunar commented on .github/sonar.yml
> +        uses: actions/setup-python@v2
it is sonar recommended, it can be changed in the next iterations

2022-11-14 13:26 UTC, rgildein submitted a review, later dismissed
LGTM

2022-11-14 13:26 UTC, rgildein commented on .github/sonar.yml
> +        run: make unittests
ack

2022-11-14 13:28 UTC, mkalcok approved these changes, later dismissed
LGTM. Thanks for this integration.

2022-11-14 13:29 UTC, rgildein submitted a review, later dismissed
LGTM

2022-11-14 13:42 UTC, mkalcok submitted a review, later dismissed

2022-11-15 06:49 UTC, Pjack approved these changes

2022-11-15 07:27 UTC, canramesh approved these changes

2022-11-15 07:38 UTC, merged

2022-11-15 07:49 UTC, rgildein commented on .coveragerc
> +output = coverage.xml
missing new line and I think we should use `pyproject.toml` instead of new file.

2022-11-15 07:49 UTC, rgildein commented on .coveragerc
> +output = coverage.xml
Can we also report an issue about using `branch = True` as we discussed yesterday?