add known limitations and code decisions
canonical/juju-verify pull request #16
Opened 2021-07-20 16:55 UTC by r-f-g

This PR provides "Known limitations" and "Code design decisions".

2021-07-21 06:33 UTC, auria requested changes
Some suggestions around wording. Structure and content look good, thanks!

2021-07-21 06:33 UTC, auria commented on README.md
> +   to remove this unit, you must perform a check on this unit or if the check is not
"In order to check if it is safe to remove this unit, juju-verify needs to be explictly run against this subordinate unit, or the unit needs to be manually checked (if juju-verify does not support this charm yet)"

2021-07-21 06:33 UTC, auria commented on README.md
> +1. If you run check on multiple units at the same time, they must all run
"If a check is run on multiple units at the same time, ..."

2021-07-21 06:33 UTC, auria commented on README.md
> +The verifier should run verification using the `verify` function, which will check
"should run verifications" (or "a verification").

2021-07-30 09:03 UTC, auria approved these changes
LGTM. I've added a suggestion for a minor fix, but it's not a blocker.

2021-07-30 10:02 UTC, r-f-g commented on README.md
> +Despite the main purpose, it is possible to use `juju-verify` as python pacakge. It
Fixed while I merge the master branch.

2021-07-30 11:21 UTC, r-f-g reviewed
recheck-snap

2021-07-30 11:59 UTC, auria approved these changes
+1, ty

2021-07-30 12:03 UTC, merged