Add format=json parameter to get-availability-zone
canonical/juju-verify pull request #32
Opened 2021-09-26 20:40 UTC by r-f-g

- add paramter format=json to get-availability-zone action
 - change custom charm to openstack-charmers-next

fixes: [#1944510](https://bugs.launchpad.net/juju-verify/+bug/1944510)

2021-09-27 11:43 UTC, auria approved these changes
LGTM.

2021-09-28 10:47 UTC, auria approved these changes
LGTM after rebase

2021-09-28 13:39 UTC, r-f-g reviewed
recheck-full

2021-09-28 14:28 UTC, r-f-g reviewed
recheck-full

2021-09-28 15:36 UTC, auria requested changes
Minor fix, otherwise +1.

2021-09-28 15:36 UTC, auria commented on README.md
> +* ceph-osd (Usable with the next stable of the charm. [cs:~openstack-charmers-next/ceph-osd] and [cs:~openstack-charmers-next/ceph-mon])
"next stable release of the charm". :)

2021-09-29 06:25 UTC, auria approved these changes
+1

2021-09-29 06:34 UTC, merged