Fix neutron-gateway verifier
canonical/juju-verify pull request #33
Opened 2021-09-27 15:26 UTC by r-f-g

- replace `get-status-routers` w/ `show-routers`
 - replace `get-status-dhcp` w/ `show-dhcp-networks`
 - replace `get-status-lb` w/ `show-loadbalancers`
 - using yaml to load actions output instead of json
 - change custom charm to openstack-charmers-next

fixes: [#1944510](https://bugs.launchpad.net/juju-verify/+bug/1944510)

2021-09-27 15:30 UTC, r-f-g commented
I deleted it in accident.

2021-09-28 09:20 UTC, r-f-g reviewed
recheck-full

2021-09-29 06:51 UTC, r-f-g reviewed
recheck-full

2021-09-29 07:16 UTC, mkalcok requested changes
reference to `neutron-gateway` charm needs to be updated also in the `docs/getting-started.rst`

2021-09-29 07:16 UTC, mkalcok commented on README.md
> +* neutron-gateway (Usable with the custom release of the charm in martin-kalcok namespace. [cs:~openstack-charmers-next/neutron-gateway])
Remove text reference to my namespace

2021-09-29 07:22 UTC, mkalcok approved these changes
LGTM

2021-09-29 08:15 UTC, merged